### ISSUE TITLE
can u help me

### ISSUE THREAD

**Issue by SlaSerX** [hotfloppy/passwd-webui#1]
Hello when i try your script i take this

Error: 500 Internal Server Error
Sorry, the requested URL 'http://185.247.118.23:8001/modify_user' caused an error:

Could not establish connection to database

What db use and where is database how i can create or upload

**Comment by hotfloppy** [comment]
> Hello when i try your script i take this
> 
> Error: 500 Internal Server Error
> Sorry, the requested URL 'http://185.247.118.23:8001/modify_user' caused an error:
> 
> Could not establish connection to database
> 
> What db use and where is database how i can create or upload

Hello! You would need to have MongoDB running and all required (requirements.txt) modules installed.

This following instructions are made based on Ubuntu 20.04:

1 - Install `Python2.7`
```
$ sudo apt install python2.7
```
2 - Install `pip2`
```
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python2.7 get-pip.py
```
3 - Install `virtualenv`
```
$ sudo pip3 install virtualenv
```
4 - Install `MongoDB`
```
$ sudo apt install mongodb
```
5 - Make sure `MongoDB` is enabled and running on startup.
```
$ sudo systemctl enable --now mongodb.service
```
6 - Clone the repo
```
$ git clone https://github.com/hotfloppy/passwd-webui.git
```
7 - Get into `passwd-webui` and activate the `virtualenv` so that we can use `pip2` modules without messing up system `pip`
```
$ cd passwd-webui
$ source venv/bin/activate
$ pip2 install -r requirements.txt
```
8 - Now everything should be ready. Starts your `passwd-webui` server:
```
$ sudo python2.7 index.py
```
8.1 - Help page:
```
$ python2.7 index.py --help
```
9 - And navigate to `http://localhost:8001` or `http://YOUR-IP:8001`.

Notes: It's better to test this on dummy account. `sudo adduser dummy-user` would suffice. Don't test this on real user account.

**Comment by SlaSerX** [comment]
its working thx
